language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - ./travis.sh

env:
  - TESTS=CI
  - TESTS=IT-DEV
  - TESTS=IT-LATEST

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
